name: cans
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake-minimal
  - medaka=1.3.3
  - seqtk
  - seqkit
  - spoa
  - porechop
  - r-base
  - r-tidyverse
  - r-plotly
  - r-data.table
  - r-scales
  - r-pastecs
  - pip
  - pip:
    - pandas