# Define workflow
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - tests
  
# Build environment
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    environment:
      PYTHON_VERSION: 3.8
    steps:
      - checkout
      - run:
          name: Clone Github Repo
          command: |
            cd $HOME
            git clone https://github.com/jimmyliu1326/CANS.git
            chmod +x CANS/CANS.sh
            export PATH="$HOME/CANS:$PATH"
      - run:
          name: Setup Miniconda
          command: |
            export MINICONDA=$HOME/miniconda
            echo "export PATH=$MINICONDA/bin:$PATH" >> $BASH_ENV
            source $BASH_ENV
            hash -r
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -f -p $MINICONDA
            conda config --set always_yes yes
            conda update conda
      - run:
          name: Setup environment and run tests
          command: |
            conda env create -f CANS/conda_env.yml
            conda activate cans
            python --version
  tests:
    docker:
      - image: cimg/base:2021.04
    environment:
      PYTHON_VERSION: 3.8
    steps:
      - checkout
      - run:
          name: Clone Github Repo
          command: |
            CANS.sh -h
