# Run Jobs
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    environment:
      PYTHON_VERSION: 3.8
    steps:
      - checkout
      - run:
          name: Clone Github Repo
          command: |
            cd $HOME
            git clone https://github.com/jimmyliu1326/CANS.git
            chmod +x CANS/CANS.sh
            echo "export PATH=$PWD/CANS:$PATH" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Setup environment
          command: |
            conda env create -f $HOME/CANS/conda_env.yml
      - run:
          name: Run Tests
          command: |
            CANS.sh -h
            source activate cans
            medaka_consensus -h
            echo $?
